apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predep-nginx-fleet
  template:
    metadata:
      name: predep-nginx-fleet-pod
      labels:
        app: predep-nginx-fleet
