resources:
  - ../../base
  - namespace.yaml
namePrefix: predep-
namespace: predep
commonLabels:
  env: predep
#patches:
patchesStrategicMerge:
  - service.yaml
  - deployment.yaml

images:
  - name: jorgejsilva/nginx-r
    newName: nginx
    newTag: latest
