apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nadegas
  name: nadegas
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nadegas
  template:
    metadata:
      labels:
        app: nadegas
    spec:
      containers:
      - image: nginx
        name: nginx
