apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fleet
spec:
  template:
    spec:
      containers:
        - name: nginx-fleet-pod
          env:
            - name: MY_KEY
              valueFrom:
                configMapKeyRef:
                  name: review-nginx-fleet-cmap
                  key: foo
