apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bundas
  name: bundas
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundas
  template:
    metadata:
      labels:
        app: bundas
    spec:
      containers:
      - image: nginx
        name: nginx
